//============================================================================
// Copyright 5AM Solutions, Inc
// Copyright Ekagra Software Technologies Ltd.
// Copyright Guidewire Architecture
// Copyright The Ohio State University Research Foundation
// Copyright Science Applications International Corporation
//
// Distributed under the OSI-approved BSD 3-Clause License.
// See http://ncip.github.com/iso21090/LICENSE.txt for details.
//============================================================================

package gov.nih.nci.iso21090.reference.convert;

import gov.nih.nci.iso21090.Constants;
import gov.nih.nci.iso21090.IdentifierReliability;
import gov.nih.nci.iso21090.IdentifierScope;
import gov.nih.nci.iso21090.Ii;
import gov.nih.nci.iso21090.NullFlavor;

/**
 * @author aevansel
 */
public class IiConverter {
    
    /**
     * @param value an II used to identify entities
     * @return a long suitable for a hibernate entity id
     */
    public static Long convertToLong(Ii value) {
        if (value == null || value.getNullFlavor() != null) {
            return null;
        }
        
        if (value.getRoot() == null) {
            throw new IllegalArgumentException("Root is required.");
        }
        
        return Long.valueOf(value.getExtension());
    }
    
    /**
     * Converts an Long to II 
     * @param value the id to convert
     * @return The Ii
     */
    public static Ii convertToIi(Long value) {
        Ii iso = new Ii();
        if (value == null) {
            iso.setNullFlavor(NullFlavor.NI);
        } else {
            iso.setExtension(value.toString());
            iso.setDisplayable(true);
            iso.setScope(IdentifierScope.OBJ);
            // change me if hibernate IDs are no longer autogenerated
            iso.setReliability(IdentifierReliability.ISS);
        }
        iso.setIdentifierName("Id");
        iso.setRoot(Constants.NCI_OID);
        return iso;
    }
}
