package gov.nih.nci.iso21090.reference.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface ISO21090ReferenceServiceConstantsBase {
	public static final String SERVICE_NS = "http://reference.iso21090.nci.nih.gov/ISO21090ReferenceService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "ISO21090ReferenceServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "ISO21090ReferenceServiceResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
