package gov.nih.nci.iso21090.reference.entities.myobject.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class MyObjectImpl extends MyObjectImplBase {

	
	public MyObjectImpl() throws RemoteException {
		super();
	}
	
  public gov.nih.nci.iso21090.extensions.Id create(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public gov.nih.nci.iso21090.reference.MyObject getById(gov.nih.nci.iso21090.extensions.Id id) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void update(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

  public void delete(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

