package gov.nih.nci.iso21090.reference.entities.myobject.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface MyObjectConstantsBase {
	public static final String SERVICE_NS = "http://reference.iso21090.nci.nih.gov/MyObject";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "MyObjectKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "MyObjectResourceProperties");
	
}
