package gov.nih.nci.iso21090.reference.service.entities.myobject.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface MyObjectI {

  public gov.nih.nci.iso21090.extensions.Id create(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException ;

  public void update(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException ;

  public void delete(gov.nih.nci.iso21090.reference.MyObject myObject) throws RemoteException ;

  public gov.nih.nci.iso21090.reference.MyObject getById(gov.nih.nci.iso21090.extensions.Id id) throws RemoteException ;

}

